# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Backend/ProReLe.Application
    - name: Build
      run: dotnet build --no-restore -c Release
      working-directory: Backend/ProReLe.Application
    - name: Test
      #run: dotnet test --no-build -c Release --verbosity normal
      run: cd Backend/ProReLe.Tests/bin/Release/net6.0; ls
      working-directory: Backend/ProReLe.Tests
